production:
  adapter: postgresql
  database: betaman
  username: betaman
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: betaman_dev
  username: uwedr
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: betaman_test
  username: uwedr
  pool: 5
  timeout: 5000
